# Site settings
title: Astrología y Renacer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://www.astrologiayrenacer.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Jekyll configuration
markdown: kramdown
encoding: utf-8
source: ./_astrologia/.tmp/src
destination: ./_astrologia/.tmp/_site
include: ["_pages"]
exclude: ["Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "favicons", "node_modules", "src", "README.md", "notas.md", "composer.phar", "composer.json", "composer.lock"]
gems:
  - jekyll-sitemap

# Plugin: jekyll-datapage_gen
page_gen-dirs: true
page_gen:
  - data: 'aforismos'
    template: 'aforismo'
    name: 'nombre'
    dir: 'aforismos'
  - data: 'planetas.index'
    template: 'planeta'
    name: 'slug'
    dir: 'planetas'
  - data: 'casas.index'
    template: 'casa'
    name: 'slug'
    dir: 'casas'
  - data: 'signos.index'
    template: 'signo'
    name: 'slug'
    dir: 'signos'