# Site settings
title: 'JR Ecotecnología'
description: 'Proveedor autorizado del programa Hipoteca Verde a nivel nacional, con 20 sucursales en 15 estados de la República Mexicana.'
logo: '/assets/img/social/logo.jpg'
iconos: '/assets/img/svg/icons.svg'
locale: 'es'
baseurl: ''
url: 'https://www.jrecotecnologia.com'
repository: 'joseanu/jrecotecnologia'

# Site owner
owner:
  name: 'JR Ecotecnología'
  email: 'contacto@jrecotecnologia.com'
  direccion:
    direccion1: 'Nicolás Romero #429'
    direccion2: 'Col. Santa Teresita'
    ciudad: 'Guadalajara'
    estado: 'Jalisco'
    cp: 44600
  telefonos:
    - 3338258247
    - 3338267767
  formsurl: '/server/contacto'
  facebook: 'https://www.facebook.com/jrecotecnologias'
  fb_app_id: 1622349154752586
  linkedin: 'https://www.linkedin.com/company/jr-ecotecnologia'
  google:
    analytics: 'UA-77266972-1'
    gtm: 'GTM-TQNGHQ'
    plus: 'https://google.com/+Jrecotecnologia'
    author: 'https://plus.google.com/110169972051158672784'
    verify: 'ZOcvun6lI3h_vsGspcSW5aeuN_i7P6ft94g-TOP_0hk'
    mapsapi: 'AIzaSyA_2f1E_wtDgpdaLNJoVTltecZEcmHpnDE'
  bing:
    verify: 'C912FFA4973B378094014CAF88EB7EB7'
  alexa:
    verify: 'Y5DYjZ4VWlrQzBP5kcQJeOKLNas'
  majestic:
    verify: 'MJ12_c11ec5d2-030d-4d5c-9018-75cf25b2ee12'

# Jekyll configuration
markdown: kramdown
encoding: 'utf-8'
source: './_jrecotec/.tmp/src'
destination: './_jrecotec/.tmp/_site'
include: ['_pages']
exclude: ['Gemfile', 'Gemfile.lock', 'gulpfile.js', 'package.json', 'favicons', 'node_modules', 'src', 'README.md', 'notas.md', 'composer.phar', 'composer.json', 'composer.lock']
plugins:
  - jekyll-sitemap

# Plugin: jekyll-datapage_gen
page_gen:
  - data: 'sucursales'
    template: 'sucursal'
    name: 'slug'
    dir: 'sucursales'
  - data: 'sucursales'
    template: 'sucursalJson'
    name: 'slug'
    dir: 'api/sucursalData'
    extension: 'json'
  - data: 'catalogo'
    page_gen-dirs: true
    template: 'ecotecnologias'
    name: 'slug'
    dir: 'ecotecnologias'
  - data: 'catalogo'
    template: 'catalogoJson'
    name: 'slug'
    dir: 'api/catalogoData'
    extension: 'json'

# Defaults
defaults:
  -
    scope:
      path: 'sucursales'
    values:
      bodyClass: 'sucursal'
      function: 'form'
  -
    scope:
      path: 'ecotecnologias'
    values:
      bodyClass: 'catalogo'
      function: 'catalogo'
      vue-meta: true

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: [development, dev]