# Site settings
title: "Green Fix Limpieza, S.A. de C.V."
description: "Limpieza y Jardinería"
logo: "/assets/img/social/logo.png"
color: "#069865"
locale: "es_MX"
baseurl: ""
url: "https://www.green-fix.com"

# Site owner
owner:
  name: "Green Fix Limpieza, S.A. de C.V."
  email: "contacto@green-fix.com"
  ciudad: "Guadalajara"
  estado: "Jalisco"
  direccion: "Mayorca 1422"
  colonia: "Lomas del Country"
  codigopostal: "44620"
  latitud: "20.699887"
  longitud: "-103.364959"
  telefonos:
    - "3333432461"
    - "3330550586"
  horario: "1-5:0900-2000,6:1000-1400"
  formsurl: "/server/contacto"
  facebook: "https://www.facebook.com/Green-Fix-Limpieza-474693915886699"
  fb_app_id: "383578788665076"
  linkedin: ""
  google:
    analytics: "UA-37123624-1"
    gtm: "GTM-K486X5X"
    plus: ""
    maps: ""
    author: ""
    verify: "gobEQTtYL2KkL3s4Hi0NGRLEMURONgkWNamZLhSnzAs"
    mapsapi: ""
  bing:
    verify: ""
  alexa:
    verify: ""

# Jekyll configuration
markdown: kramdown
encoding: utf-8
source: ./_greenfix/.tmp/src
destination: ./_greenfix/.tmp/_site
include: ["_pages"]
exclude: ["Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "favicons", "node_modules", "src", "README.md", "notas.md", "composer.phar", "composer.json", "composer.lock"]
gems:
  - jekyll-sitemap

# Colecciones
#collections:
#  ecotecnologias:
#    output: true
#    permalink: /:collection/:path/

# Defaults
#defaults:
#  -
#    scope:
#      path: "sucursales"
#    values:
#      bodyClass: "sucursal"
#      function: "form"

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: [development, dev]